// Package rules provides MailReaper rule definitions and evaluation helpers.
package rules

import "github.com/kraftbj/mailreaper/internal/db"

// DefaultRules contains the built-in rules shipped with MailReaper.
// These mirror the DEFAULT_RULES array from the Thunderbird extension's
// rules/defaults.js. IDs, names, patterns, priorities, and settings match exactly.
var DefaultRules = []db.Rule{
	{
		ID:       "builtin-expires-header",
		Name:     "Emails with Expires header (RFC standard)",
		Enabled:  true,
		Priority: 1, // Highest priority — if sender set it, honor it
		Builtin:  true,
		MatchConfig: db.MatchConfig{
			SenderPatterns:  []string{},
			SubjectPatterns: []string{},
			Folders:         []string{},
			HeaderMatch:     map[string]string{},
		},
		ExpirationConfig: db.ExpirationConfig{
			Type: "header",
		},
		Action:            "move",
		DestinationFolder: "",
		GracePeriodDays:   3,
	},
	{
		ID:       "builtin-otp-codes",
		Name:     "One-time codes & verification emails",
		Enabled:  true,
		Priority: 10,
		Builtin:  true,
		MatchConfig: db.MatchConfig{
			Folders:        []string{},
			SenderPatterns: []string{},
			SubjectPatterns: []string{
				"*verification code*",
				"*verify your*",
				"*one-time*",
				"*OTP*",
				"*login code*",
				"*security code*",
				"*confirm your email*",
				"*authentication code*",
				"*two-factor*",
				"*2FA*",
				"*sign-in code*",
				"*passcode*",
				"*your * code is*",
				"*your * code:*",
				"*your code is*",
				"*your code:*",
				"*confirmation code*",
				"*access code*",
				"*temporary password*",
				"*magic link*",
				"*sign in to*",
				"*log in to*",
			},
			HeaderMatch: map[string]string{},
		},
		ExpirationConfig: db.ExpirationConfig{
			Type:  "ttl",
			Hours: 1,
		},
		Action:            "move",
		DestinationFolder: "",
		GracePeriodDays:   1,
	},
	{
		ID:       "builtin-transit-alerts",
		Name:     "Transit delay & service alerts",
		Enabled:  false, // Disabled by default — user enables if relevant
		Priority: 15,
		Builtin:  true,
		MatchConfig: db.MatchConfig{
			Folders: []string{},
			SenderPatterns: []string{
				"*@capmetro.org",
				"*@transitapp.com",
				"*@metro.net",
				"*@mta.info",
				"*@bart.gov",
			},
			SubjectPatterns: []string{
				"*delay*",
				"*service alert*",
				"*disruption*",
				"*suspended*",
				"*detour*",
			},
			HeaderMatch: map[string]string{},
		},
		ExpirationConfig: db.ExpirationConfig{
			Type:  "ttl",
			Hours: 2,
		},
		Action:            "move",
		DestinationFolder: "",
		GracePeriodDays:   1,
	},
	{
		ID:       "builtin-shipping-delivered",
		Name:     "Package delivery confirmations",
		Enabled:  true,
		Priority: 20,
		Builtin:  true,
		MatchConfig: db.MatchConfig{
			Folders: []string{},
			SenderPatterns: []string{
				"*@ups.com",
				"*@fedex.com",
				"*@usps.com",
				"*@dhl.com",
				"*@amazonses.com",
				"*@amazon.com",
			},
			SubjectPatterns: []string{
				"*delivered*",
				"*has been delivered*",
				"*was delivered*",
			},
			HeaderMatch: map[string]string{},
		},
		ExpirationConfig: db.ExpirationConfig{
			Type:  "ttl",
			Hours: 72,
		},
		Action:            "move",
		DestinationFolder: "",
		GracePeriodDays:   7,
	},
	{
		ID:       "builtin-calendar-reminders",
		Name:     "Calendar event reminders",
		Enabled:  true,
		Priority: 25,
		Builtin:  true,
		MatchConfig: db.MatchConfig{
			Folders: []string{},
			SenderPatterns: []string{
				"*calendar-notification*@google.com",
				"*@calendly.com",
			},
			SubjectPatterns: []string{
				"*reminder:*",
				"*starts in*",
				"*upcoming event*",
			},
			HeaderMatch: map[string]string{},
		},
		ExpirationConfig: db.ExpirationConfig{
			Type:  "ttl",
			Hours: 24,
		},
		Action:            "move",
		DestinationFolder: "",
		GracePeriodDays:   1,
	},
	{
		ID:       "builtin-receipts",
		Name:     "Receipts & statements → Paper-Trail",
		Enabled:  false,
		Priority: 30,
		Builtin:  true,
		MatchConfig: db.MatchConfig{
			Folders: []string{},
			SenderPatterns: []string{
				"*@paypal.com",
				"*@venmo.com",
				"*@square.com",
				"*@stripe.com",
				"*@shopify.com",
				"*@toast-restaurant.com",
				"*@amazonses.com",
				"*@apple.com",
				"*@amazon.com",
				"*@google.com",
				"*@microsoft.com",
				"*receipt*@*",
				"*billing*@*",
				"*invoice*@*",
			},
			SubjectPatterns: []string{
				"*receipt*",
				"*invoice*",
				"*payment*",
				"*order confirmation*",
				"*purchase confirmation*",
				"*billing statement*",
				"*your order*",
				"*transaction*",
				"*subscription*renew*",
				"*your * statement*",
			},
			HeaderMatch: map[string]string{},
		},
		ExpirationConfig: db.ExpirationConfig{
			Type: "classify",
		},
		Action:            "move",
		DestinationFolder: "Paper-Trail",
		GracePeriodDays:   0,
	},
	{
		ID:       "builtin-llm-promo-scanner",
		Name:     "AI: Scan promotions for deadlines",
		Enabled:  false, // Disabled until LLM is configured
		Priority: 100,   // Low priority — only if no static rule matched
		Builtin:  true,
		MatchConfig: db.MatchConfig{
			Folders:        []string{}, // User should set to their promo/deals folder
			SenderPatterns: []string{},
			SubjectPatterns: []string{
				"*sale*",
				"*% off*",
				"*discount*",
				"*limited time*",
				"*ends*",
				"*expires*",
				"*last chance*",
				"*final hours*",
				"*today only*",
				"*flash*",
				"*clearance*",
				"*coupon*",
				"*deal*",
			},
			HeaderMatch: map[string]string{},
		},
		ExpirationConfig: db.ExpirationConfig{
			Type: "llm",
		},
		Action:            "move",
		DestinationFolder: "",
		GracePeriodDays:   3,
	},
	{
		ID:       "builtin-llm-receipt-scanner",
		Name:     "AI: Detect receipts & statements",
		Enabled:  false,
		Priority: 200,
		Builtin:  true,
		MatchConfig: db.MatchConfig{
			Folders:         []string{},
			SenderPatterns:  []string{},
			SubjectPatterns: []string{},
			HeaderMatch:     map[string]string{},
		},
		ExpirationConfig: db.ExpirationConfig{
			Type:     "llm-classify",
			Category: "receipt",
		},
		Action:            "move",
		DestinationFolder: "Paper-Trail",
		GracePeriodDays:   0,
	},
	{
		ID:       "builtin-travel-alerts",
		Name:     "Travel alerts & flight notifications",
		Enabled:  false, // Disabled by default — user enables if relevant
		Priority: 16,
		Builtin:  true,
		MatchConfig: db.MatchConfig{
			Folders: []string{},
			SenderPatterns: []string{
				"*@tripit.com",
				"*@email.tripit.com",
				"*@flightaware.com",
				"*@notifications.google.com",
				"*@southwest.com",
				"*@t.united.com",
				"*@e.delta.com",
				"*@aa.com",
				"*@jetblue.com",
				"*@email-marriott.com",
				"*@hilton.com",
			},
			SubjectPatterns: []string{
				"*flight*alert*",
				"*flight*delay*",
				"*flight*cancel*",
				"*flight*change*",
				"*gate change*",
				"*check-in*",
				"*check in*now*",
				"*boarding pass*",
				"*itinerary*update*",
				"*travel alert*",
				"*trip reminder*",
			},
			HeaderMatch: map[string]string{},
		},
		ExpirationConfig: db.ExpirationConfig{
			Type:  "ttl",
			Hours: 24,
		},
		Action:            "move",
		DestinationFolder: "",
		GracePeriodDays:   1,
	},
	{
		ID:       "builtin-llm-newsletter-scanner",
		Name:     "AI: Detect newsletters & digests",
		Enabled:  false,
		Priority: 201,
		Builtin:  true,
		MatchConfig: db.MatchConfig{
			Folders:         []string{},
			SenderPatterns:  []string{},
			SubjectPatterns: []string{},
			HeaderMatch:     map[string]string{},
		},
		ExpirationConfig: db.ExpirationConfig{
			Type:     "llm-classify",
			Category: "newsletter",
		},
		Action:            "move",
		DestinationFolder: "Folders/AI-Triage/Newsletters",
		GracePeriodDays:   0,
	},
	{
		ID:       "builtin-llm-notification-scanner",
		Name:     "AI: Detect notifications & alerts",
		Enabled:  false,
		Priority: 202,
		Builtin:  true,
		MatchConfig: db.MatchConfig{
			Folders:         []string{},
			SenderPatterns:  []string{},
			SubjectPatterns: []string{},
			HeaderMatch:     map[string]string{},
		},
		ExpirationConfig: db.ExpirationConfig{
			Type:     "llm-classify",
			Category: "notification",
		},
		Action:            "move",
		DestinationFolder: "Folders/AI-Triage/Notifications",
		GracePeriodDays:   0,
	},
	{
		ID:       "builtin-llm-hobbies-scanner",
		Name:     "AI: Detect hobbies & gaming",
		Enabled:  false,
		Priority: 203,
		Builtin:  true,
		MatchConfig: db.MatchConfig{
			Folders:         []string{},
			SenderPatterns:  []string{},
			SubjectPatterns: []string{},
			HeaderMatch:     map[string]string{},
		},
		ExpirationConfig: db.ExpirationConfig{
			Type:     "llm-classify",
			Category: "hobbies",
		},
		Action:            "move",
		DestinationFolder: "Folders/AI-Triage/Hobbies",
		GracePeriodDays:   0,
	},
	{
		ID:       "builtin-llm-promotion-scanner",
		Name:     "AI: Detect promotions & marketing",
		Enabled:  false,
		Priority: 203,
		Builtin:  true,
		MatchConfig: db.MatchConfig{
			Folders:         []string{},
			SenderPatterns:  []string{},
			SubjectPatterns: []string{},
			HeaderMatch:     map[string]string{},
		},
		ExpirationConfig: db.ExpirationConfig{
			Type:     "llm-classify",
			Category: "promotion",
		},
		Action:            "move",
		DestinationFolder: "Folders/AI-Triage/Promotions",
		GracePeriodDays:   0,
	},
	{
		ID:       "builtin-llm-catch-all",
		Name:     "AI: Catch-all expiration scanner",
		Enabled:  false, // Disabled until LLM is configured
		Priority: 999,   // Lowest priority — only if no other rule matched
		Builtin:  true,
		MatchConfig: db.MatchConfig{
			Folders:         []string{},
			SenderPatterns:  []string{},
			SubjectPatterns: []string{},
			HeaderMatch:     map[string]string{},
		},
		ExpirationConfig: db.ExpirationConfig{
			Type: "llm",
		},
		Action:            "move",
		DestinationFolder: "",
		GracePeriodDays:   7,
	},
}
